-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.reality_series
(
    slug          character varying COLLATE pg_catalog."default" NOT NULL,
    created_at    timestamp with time zone                       NOT NULL DEFAULT now(),
    title         character varying COLLATE pg_catalog."default" NOT NULL,
    updated_at    timestamp with time zone                       NOT NULL DEFAULT now(),
    premiere_time timestamp with time zone,
    in_progress   boolean                                        NOT NULL,
    logo_src      character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT reality_series_pkey PRIMARY KEY (slug)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.reality_series
    OWNER to postgres;

ALTER TABLE IF EXISTS public.reality_series
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.reality_series TO anon;

GRANT ALL ON TABLE public.reality_series TO authenticated;

GRANT ALL ON TABLE public.reality_series TO postgres;

GRANT ALL ON TABLE public.reality_series TO service_role;
CREATE POLICY "Enable access to all users"
    ON public.reality_series
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

insert into public.reality_series (slug, created_at, title, updated_at, premiere_time, in_progress, logo_src)
values ('survivor_us', now(), 'Survivor (US)', now(), null, false, 'Survivor_US_42_Logo');
