-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.seasons
(
    id             uuid                                           NOT NULL DEFAULT uuid_generate_v4(),
    updated_at     timestamp with time zone                       NOT NULL DEFAULT now(),
    "order"        bigint                                         NOT NULL,
    title          character varying COLLATE pg_catalog."default" NOT NULL,
    logo_src       character varying COLLATE pg_catalog."default" NOT NULL,
    reality_series character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT seasons_pkey PRIMARY KEY (id),
    CONSTRAINT seasons_reality_series_fkey FOREIGN KEY (reality_series)
        REFERENCES public.reality_series (slug) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.seasons
    OWNER to postgres;

ALTER TABLE IF EXISTS public.seasons
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.seasons TO anon;

GRANT ALL ON TABLE public.seasons TO authenticated;

GRANT ALL ON TABLE public.seasons TO postgres;

GRANT ALL ON TABLE public.seasons TO service_role;
CREATE POLICY "Enable access to all users"
    ON public.seasons
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
