-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.league_participants
(
    id          uuid                     NOT NULL DEFAULT uuid_generate_v4(),
    created_at  timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    league      uuid                     NOT NULL DEFAULT uuid_generate_v4(),
    participant uuid                     NOT NULL DEFAULT uuid_generate_v4(),
    CONSTRAINT league_participants_pkey PRIMARY KEY (id),
    CONSTRAINT league_participants_league_fkey FOREIGN KEY (league)
        REFERENCES public.leagues (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT league_participants_participant_fkey FOREIGN KEY (participant)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.league_participants
    OWNER to postgres;

ALTER TABLE IF EXISTS public.league_participants
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.league_participants TO anon;

GRANT ALL ON TABLE public.league_participants TO authenticated;

GRANT ALL ON TABLE public.league_participants TO postgres;

GRANT ALL ON TABLE public.league_participants TO service_role;

ALTER TABLE IF EXISTS public.leagues
    ADD COLUMN format character varying COLLATE pg_catalog."default" DEFAULT ''::character varying;

CREATE TABLE IF NOT EXISTS public.lp_contestants
(
    id                 uuid NOT NULL DEFAULT uuid_generate_v4(),
    contestant_season  uuid NOT NULL DEFAULT uuid_generate_v4(),
    league_participant uuid NOT NULL DEFAULT uuid_generate_v4(),
    rank               character varying COLLATE pg_catalog."default",
    CONSTRAINT lp_contestants_pkey PRIMARY KEY (id),
    CONSTRAINT lp_contestants_contestant_season_fkey FOREIGN KEY (contestant_season)
        REFERENCES public.contestant_seasons (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT lp_contestants_league_participant_fkey FOREIGN KEY (league_participant)
        REFERENCES public.league_participants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.lp_contestants
    OWNER to postgres;

ALTER TABLE IF EXISTS public.lp_contestants
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.lp_contestants TO anon;

GRANT ALL ON TABLE public.lp_contestants TO authenticated;

GRANT ALL ON TABLE public.lp_contestants TO postgres;

GRANT ALL ON TABLE public.lp_contestants TO service_role;
