export const Contestants = {
  BRANDON: {
    name: "Brandon Cottom",
    age: 30,
    hometown: "Newton, PA",
    occupation: "Security Specialist",
  },
  BRUCE: {
    name: "Bruce Perreault",
    age: 46,
    hometown: "Warwick, RI",
    occupation: "Insurance Agent",
  },
  CAROLYN: {
    name: "Carolyn Wiger",
    age: 36,
    hometown: "Hugo, MN",
    occupation: "Drug Counselor",
  },
  CARSON: {
    name: "Carson Garrett",
    age: 21,
    hometown: "Atlanta, GA",
    occupation: "NASA Engineering Student",
  },
  CLAIRE: {
    name: "Claire Rafson",
    age: 25,
    hometown: "Brooklyn, NY",
    occupation: "Tech Investor",
  },
  DANNY: {
    name: "Danny Massa",
    age: 32,
    hometown: "Bronx, NY",
    occupation: "Firefighter",
  },
  FRANNIE: {
    name: "Frannie Marin",
    age: 23,
    hometown: "Cambridge, MA",
    occupation: "Research Coordinator",
  },
  HEIDI: {
    name: "Heidi Lagares-Greenblatt",
    age: 43,
    hometown: "Pittsburgh, PA",
    occupation: "Engineering Manager",
  },
  HELEN: {
    name: "Helen Li",
    age: 29,
    hometown: "San Francisco, CA",
    occupation: "Product Manager",
  },
  JAIME: {
    name: "Jaime Lynn Ruiz",
    age: 35,
    hometown: "Mesa, AZ",
    occupation: "Yogi",
  },
  JOSH: {
    name: "Josh Wilder",
    age: 34,
    hometown: "Atlanta, GA",
    occupation: "Surgical Podiatrist",
  },
  KANE: {
    name: "Kane Fritzler",
    age: 25,
    hometown: "Saskatoon, Saskatchewan",
    occupation: "Law Student",
  },
  LAUREN: {
    name: "Lauren Harpe",
    age: 31,
    hometown: "Mont Belvieu, TX",
    occupation: "Elementary School Teacher",
  },
  MADDY: {
    name: "Maddy Pomilla",
    age: 28,
    hometown: "Brooklyn, NY",
    occupation: "Charity Projects Manager",
  },
  MATT: {
    name: "Matt Blankenship",
    age: 27,
    hometown: "San Francisco, CA",
    occupation: "Security Software Engineer",
  },
  MATTHEW: {
    name: "Matthew Grinstead-Mayle",
    age: 43,
    hometown: "Columbus, OH",
    occupation: "Barbershop Owner",
  },
  SARAH: {
    name: "Sarah Wade",
    age: 27,
    hometown: "Chicago, IL",
    occupation: "Management Consultant",
  },
  YAM_YAM: {
    name: "Yam_Yam Arocho",
    age: 36,
    hometown: "San Juan, Puerto Rico",
    occupation: "Salon Owner",
  },
};
