schema:
  - http://localhost:54321/graphql/v1:
      headers:
        apiKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU
documents: './features/**/*.ts'
extensions:
  languageService:
    cacheSchemaFileForLookup: true